### ISSUE TITLE
Using PowerUps from Empty Array causes game crash

### ISSUE THREAD

**Issue by ogdenm** [EntelectChallenge/2020-Overdrive#96]
=======================================
Starting round: 13 
=======================================

======================================================================================================
round:13
player: id:1 position: y:3 x:19 speed:0 state:NOTHING statesThatOccurredThisRound:NOTHING boosting:false boost-counter:0 damage:6 score:-26 powerups: 
opponent: id:2 position: y:4 x:26 speed:0

[░░░░░░▓░░░#▓░░░░░░»░Φ░░░T░]
[░░░░░#░░░░░▓░░░░░▓░░░░░░░░]
[░░░░#1░░░░░▓░░░░░░▓░░░░░░▓]
[░░░▓░░░░░░░░2░░░░░░▓░░░░▓░]
======================================================================================================
C;13;USE_BOOST
C;13;ACCELERATE
=======================================
Completed round: 13 
=======================================

Failed to write global round information
java.util.NoSuchElementException: last of empty array
	at scala.collection.ArrayOps$.last$extension(ArrayOps.scala:229) ~[?:?]
	at za.co.entelect.challenge.game.contracts.renderer.JsonRenderer.$anonfun$renderVisualiserMap$1(JsonRenderer.scala:73) ~[?:?]
	at scala.collection.immutable.List.map(List.scala:219) ~[?:?]
	at za.co.entelect.challenge.game.contracts.renderer.JsonRenderer.renderVisualiserMap(JsonRenderer.scala:66) ~[?:?]
	at za.co.entelect.challenge.game.contracts.renderer.BaseMapRenderer.render(BaseMapRenderer.scala:21) ~[?:?]
	at za.co.entelect.challenge.engine.runner.GameEngineRunner.onRoundComplete(GameEngineRunner.java:173) [game-runner-jar-with-dependencies.jar:?]
	at za.co.entelect.challenge.engine.runner.GameEngineRunner.runMatch(GameEngineRunner.java:63) [game-runner-jar-with-dependencies.jar:?]
	at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.run(GameBootstrapper.java:87) [game-runner-jar-with-dependencies.jar:?]
	at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.main(GameBootstrapper.java:47) [game-runner-jar-with-dependencies.jar:?]
Exception during match execution
java.util.NoSuchElementException: last of empty array
	at scala.collection.ArrayOps$.last$extension(ArrayOps.scala:229) ~[?:?]
	at za.co.entelect.challenge.game.contracts.map.CarGameMap.$anonfun$getWinningPlayer$1(CarGameMap.scala:31) ~[?:?]
	at za.co.entelect.challenge.game.contracts.map.CarGameMap.$anonfun$getWinningPlayer$1$adapted(CarGameMap.scala:28) ~[?:?]
	at scala.collection.immutable.Range.foreach(Range.scala:190) ~[?:?]
	at za.co.entelect.challenge.game.contracts.map.CarGameMap.getWinningPlayer(CarGameMap.scala:28) ~[?:?]
	at za.co.entelect.challenge.game.contracts.game.CarGameEngine.isGameComplete(CarGameEngine.scala:9) ~[?:?]
	at za.co.entelect.challenge.engine.runner.GameEngineRunner.isGameComplete(GameEngineRunner.java:221) ~[game-runner-jar-with-dependencies.jar:?]
	at za.co.entelect.challenge.engine.runner.GameEngineRunner.runMatch(GameEngineRunner.java:60) ~[game-runner-jar-with-dependencies.jar:?]
	at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.run(GameBootstrapper.java:87) [game-runner-jar-with-dependencies.jar:?]
	at za.co.entelect.challenge.engine.bootstrapper.GameBootstrapper.main(GameBootstrapper.java:47) [game-runner-jar-with-dependencies.jar:?]

**Comment by KyleMcAllister** [comment]
Hello @ogdenm thank you for picking this up. Seems to be an issue with boost, oil and lizard powerups. This will be fixed in the next release
